include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    # Ignore generated files
    - "**/*.g.dart"
    - "lib/src/generated/*.dart"
linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    public_member_api_docs: false
    prefer_relative_imports: false
