name: Build (Linux, Mac OS, Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    name: "Build Windows"
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3.0.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.3.0
        with:
          channel: beta


      - name: Enable desktop
        run: flutter config --enable-windows-desktop

      - name: Get packages
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Flutter build app
        run: flutter build windows
